version: '3'
services:
  app:
    image: mohammed87244/node-web-app
    ports:
    - "5008:5008"
  healthcheck:
    test: curl --fail http://localhost:3000/health || exit 1
    interval: 30s
    timeout: 10s
    retries: 3
  restart: always